### ISSUE TITLE
Add space in meta line

### ISSUE THREAD

**Issue by BmanDesignsCanada** [SaskArtists/SaskArtists#110]
Error: Bad value 1;url=index.php for attribute content on element meta: Expected a space character, but saw u instead.
From line 5, column 9; to line 5, column 61
`<meta http-equiv="refresh" content="1;url=index.php">`

**Comment by rye761** [comment]
In which file does this issue occur?

**Comment by rye761** [comment]
Looks like it was fixed by code tidy automatically. The issue occurred in the index.html file.
