### ISSUE TITLE
Add Missing Artist Descriptions

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#182]
Most artists on the database have a brief description. These two do not.

Missing:
- [ ] Ryan Arnott
- [ ] Micheal Bromley
- [ ] David Thauberger

**Comment by gemohandy** [comment]
From what I can tell, this requires database access. I am unassigning myself from it. If I am wrong, please reassign me.

**Comment by BmanDesignsCanada** [comment]
This needs MySQL

**Comment by rye761** [comment]
- [x] rpoitras
- [x] reginabellringers.ca
- [x] mkennedy
- [x] mdavenport

**Comment by gemohandy** [comment]
So, we have a new homepage now. It doesn't have artist descriptions on it. Yet. 
Are we putting artist descriptions on the new homepage? If so, we still need to address this. If not, we can probably close it - no need to add something we aren't going to use, right?

**Comment by synixebrett** [comment]
I am moving to the backlog and removing the MySQL label, this will be done next year hopefully, but will require design changes to the list of artists.

**Comment by gemohandy** [comment]
It's "next year". Commenting to remind you about it.
