### ISSUE TITLE
Make Letters Line Up With Image

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#183]
Regardless of the dimensions of the image being displayed, the letters overflow, forcing Z and the Group tab to be on a new line. Either make the picture wider, or make the tabs narrower, or do something else to fix it.

**Comment by BmanDesignsCanada** [comment]
Either @kzastrow01 or @RhiRhi102 fix this

**Comment by rye761** [comment]
Another option to fix this is to eliminate tabs that do not have any artists under them.

**Comment by gemohandy** [comment]
That is only a temporary solution. We will continue to get new artists, and the existence of empty tabs is not a constant. I do not know about you, but I would rather avoid simply pushing this problem off to future campers and mentors.

**Comment by rye761** [comment]
Either way, it would still be good to eliminate unnecessary tabs. The amount of tabs able to fit on one line is different depending on the size of the monitor the user is using. Therefore, there isn't a global solution if we choose to keep the tabs. Inevitably, on small screens (such as a tablet or phone) multiple lines will need to be used.

We may want to think about a better system for sorting that better accommodates all screen sizes before making extensive modifications to the current tab system.

**Comment by synixebrett** [comment]
Closing in favor of a new homepage
