### ISSUE TITLE
Auto-scroll jumpiness

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#195]
The photo album on the index page automatically scrolls. Different images have different dimensions. This causes problems, as the stuff underneath jumps up and down depending on the resolution. While the autoscrolling does stop if you click on one of the arrows, it continues indefinitely otherwise. Something should probably be done to prevent the jumping, as it can be annoying while simply browsing the database.

**Comment by BmanDesignsCanada** [comment]
The image dimensions need to be made static. Black bars to fill in empty space.
