### ISSUE TITLE
Emma Lake Link Style

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#199]
The links on the "Artists Involved" page have a different format than those on any other page. This should probably be fixed by adding the format to the other pages.

**Comment by BmanDesignsCanada** [comment]
Do not work on Emma Lake at this time.

**Comment by gemohandy** [comment]
@BmanDesignsCanada - Now that issue #77 is solved, should @mreddekopp work on this?

**Comment by BmanDesignsCanada** [comment]
Not yet

**Comment by gemohandy** [comment]
May I ask why?

**Comment by gemohandy** [comment]
...Are we still waiting on this?

**Comment by AndrewJMD** [comment]
#417
