### ISSUE TITLE
McGregor Hone Sask Artists Link

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#206]
The link back to the Sask Artists Database page on McGregor Hone's page is broken. It does not lead back to the Sask Artists Database; it goes to http://art.27charisma.com/

**Comment by gemohandy** [comment]
@BmanDesignsCanada - Did you fix this when you moved the file? It doesn't seem to be a problem in the Github version.

**Comment by BmanDesignsCanada** [comment]
Yes, this is fixed.
