### ISSUE TITLE
Marilyn Levine Sask Artists Link

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#210]
Marilyn Levine's Sask Artist link goes to http://art.27charisma.com/

**Comment by gemohandy** [comment]
This seems to be a similar case to #206. Again, @BmanDesignsCanada, did you fix it on the Github version? Neither of the two seem to even be a problem on SaskArtists anymore!

**Comment by BmanDesignsCanada** [comment]
Why not.
