### ISSUE TITLE
Missing Folders

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#229]
Some folders seem to not exist on the repository despite definitely existing on the Sask Artists page. Examples:
- [x] hbenning
- [x] mbromley
- [x] mhone
- [x] mlevine
- [x] dthauberger

**Comment by gemohandy** [comment]
I am unable to solve #210 or #206 without these missing folders.

**Comment by BmanDesignsCanada** [comment]
We are missing quite a few, more than just those 5. I am working on adding them all in.

**Comment by BmanDesignsCanada** [comment]
-[x] dross
-[x] jkenderdine
-[x] wperreault
