### ISSUE TITLE
Update Wynona Mulcaster Age

### ISSUE THREAD

**Issue by rye761** [SaskArtists/SaskArtists#237]
Unfortunately, she died at 101. This information should be reflected on her page.

http://sknac.ca/index.php?page=NewsDetail&id=75

**Comment by gemohandy** [comment]
I am unable to complete this issue at present. Wynona Mulcaster's folder only has the images. It lacks the CSS and the HTML. Please fix the repository!

**Comment by rye761** [comment]
That issue has been fixed.
