### ISSUE TITLE
Jack Cowin Copyright Info

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#245]
We need to add the copyright info on Jack Cowin's website. Allegedly, the site was created by Zain Khan in 2016. You also need to attribute the artist info and the update that is being made right here.

**Comment by gemohandy** [comment]
Assigning this to Rhi because she has already messed with these files.

**Comment by BmanDesignsCanada** [comment]
Don't work on these changes until I can double check you know how to branch for this properly.

**Comment by BmanDesignsCanada** [comment]
Links also don't work.
