### ISSUE TITLE
No Style on Disclaimer

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#285]
The disclaimer page [here](http://saskartists.ca/disclaimer.html) has no style. None. 
Okay, maybe the purple title is a bit of style, but still. Obvious problems.

**Comment by BmanDesignsCanada** [comment]
We may work on this in the future.

**Comment by synixebrett** [comment]
The disclaimer should be redone as part of the new homepage, closing in favor of #322
