### ISSUE TITLE
Move Artists into Directory

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#295]
Instead of having all the artists in the root directory I would like to have them moved to a folder named artists. I also want a URL Rewrite to keep the existing URLs. http://saskartists.ca/mhone should show files from saskartists.ca/artists/mhone.

This will make the root directory cleaner without breaking links.

**Comment by gemohandy** [comment]
@synixebrett - Did you forget about the URL Rewrite? That's why the links don't work.
