### ISSUE TITLE
vcicansky

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#304]
Create 3 galleries

- [x] Vegetables Gallery
- [ ] Working Class
- [x] Benches

**Comment by trollmad3** [comment]
How would this work? I see a lot of vegetable related images on his site and wording class and so on. Do I just create a new page on there website that is vegetable related and working class + the other ones.

**Comment by trollmad3** [comment]
This looks easy to do. Do I just create a menu showing the galleries?

**Comment by trollmad3** [comment]
@synixebrett Do I create a separate menu for the galleries?

**Comment by trollmad3** [comment]
Done the veggie gallery. I just need to fix the arrows, and I do not know how.

![2018-08-19_17-24-47](https://user-images.githubusercontent.com/7843719/44317435-842ebe80-a3ee-11e8-92e2-d0a82f2654d5.gif)
