### ISSUE TITLE
Make gallery link easier to find dgilhooy

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#310]

**Comment by trollmad3** [comment]
![image](https://user-images.githubusercontent.com/7843719/43032319-28f483d6-8c71-11e8-8149-fd1709b56ae3.png)
If you're talking about this I can see it perfectly fine. What do you mean by easier?

**Comment by AndrewJMD** [comment]
investigated and couldn't find any issue with the gallery link
