### ISSUE TITLE
tmarner and marner

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#321]
While composing a list of missing artists, I noticed that Terrace John Marner has two folders - tmarner and marner. The former is currently accessible through normal means. The two folders should be consolidated together in some way. Wayne would likely request both versions are somehow preserved for the sake of history - maybe just remove the big text block, and make the marner one a second gallery?

**Comment by gemohandy** [comment]
Yeah, you know how I suggested integrating the two together? I've changed my mind. The one in the marner folder was generated in Adobe PageMill 2.0 Mac. I don't think that's as bad as #385, but it still doesn't seem good. Give me boring old hand-written HTML any day. Just get rid of the marner folder.

**Comment by synixebrett** [comment]
I'm going to leave it there for now. That page is from the late 1990s and should be kept around. I'm thinking we should create an archive folder, where we put old websites that have been replaced with more modern pages. This will be a separate issue though.

**Comment by synixebrett** [comment]
I just noticed the page claims to have been created in 2009. Why was 12 year old Adobe software being used to develop websites...
