### ISSUE TITLE
CircleCI Compliance

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#324]
We have a testing thing. We need to make sure we can actually use it to test new things. This means fixing the old things.

List of issues (copied/pasted from thing):

- [x] Undescriptive name: ./artists.js
- [x] Undescriptive name: ./acrease/b1a.gif
- [x] Undescriptive name: ./acrease/b2a.gif
- [x] Undescriptive name: ./acrease/b3a.gif
- [x] Undescriptive name: ./acrease/b4a.gif
- [x] Undescriptive name: ./acrease/bio.gif
- [x] Undescriptive name: ./acrease/gal.swf
- [x] Undescriptive name: ./acrease/top.gif
- [x] Invalid Character (: ./afyfe/(1).JPG
- [x] Invalid Character ): ./afyfe/(1).JPG
- [x] Undescriptive name: ./afyfe/(1).JPG
- [x] Invalid Character (: ./afyfe/(10).JPG
- [x] Invalid Character ): ./afyfe/(10).JPG
- [x] Invalid Character (: ./afyfe/(11).JPG
- [x] Invalid Character ): ./afyfe/(11).JPG
- [x] Invalid Character (: ./afyfe/(12).JPG
- [x] Invalid Character ): ./afyfe/(12).JPG
- [x] Invalid Character (: ./afyfe/(13).JPG
- [x] Invalid Character ): ./afyfe/(13).JPG
- [x] Invalid Character (: ./afyfe/(15).JPG
- [x] Invalid Character ): ./afyfe/(15).JPG
- [x] Invalid Character (: ./afyfe/(16).JPG
- [x] Invalid Character ): ./afyfe/(16).JPG
- [x] Invalid Character (: ./afyfe/(17).JPG
- [x] Invalid Character ): ./afyfe/(17).JPG
- [x] Invalid Character (: ./afyfe/(18).JPG
- [x] Invalid Character ): ./afyfe/(18).JPG
- [x] Invalid Character (: ./afyfe/(19).JPG
- [x] Invalid Character ): ./afyfe/(19).JPG
- [x] Invalid Character (: ./afyfe/(2).JPG
- [x] Invalid Character ): ./afyfe/(2).JPG
- [x] Undescriptive name: ./afyfe/(2).JPG
- [x] Invalid Character (: ./afyfe/(3).JPG
- [x] Invalid Character ): ./afyfe/(3).JPG
- [x] Undescriptive name: ./afyfe/(3).JPG
- [x] Invalid Character (: ./afyfe/(4).JPG
- [x] Invalid Character ): ./afyfe/(4).JPG
- [x] Undescriptive name: ./afyfe/(4).JPG
- [x] Invalid Character (: ./afyfe/(5).JPG
- [x] Invalid Character ): ./afyfe/(5).JPG
- [x] Undescriptive name: ./afyfe/(5).JPG
- [x] Invalid Character (: ./afyfe/(6).JPG
- [x] Invalid Character ): ./afyfe/(6).JPG
- [x] Undescriptive name: ./afyfe/(6).JPG
- [x] Invalid Character (: ./afyfe/(7).JPG
- [x] Invalid Character ): ./afyfe/(7).JPG
- [x] Undescriptive name: ./afyfe/(7).JPG
- [x] Invalid Character (: ./afyfe/(8).JPG
- [x] Invalid Character ): ./afyfe/(8).JPG
- [x] Undescriptive name: ./afyfe/(8).JPG
- [x] Invalid Character (: ./afyfe/(9).JPG
- [x] Invalid Character ): ./afyfe/(9).JPG
- [x] Undescriptive name: ./afyfe/(9).JPG
- [x] Space in filename:  ./afyfe/Headline - Copy.jpg
- [x] Undescriptive name: ./afyfe/art1.html
- [x] Undescriptive name: ./afyfe/art2.html
- [x] Undescriptive name: ./afyfe/art3.html
- [x] Undescriptive name: ./afyfe/art4.html
- [x] Undescriptive name: ./afyfe/art5.html
- [x] Undescriptive name: ./afyfe/art6.html
- [x] Space in filename:  ./afyfe/atthebeach - Copy.jpg
- [x] Space in filename:  ./afyfe/atthebeach2 - Copy.jpg
- [x] Space in filename:  ./afyfe/morning - Copy.jpg
- [x] Space in filename:  ./afyfe/morning2 - Copy.jpg
- [x] Space in filename:  ./afyfe/mossyrocks - Copy.jpg
- [x] Space in filename:  ./afyfe/mossyrocks2 - Copy.jpg
- [x] Space in filename:  ./afyfe/natureresting - Copy.jpg
- [x] Space in filename:  ./afyfe/natureresting2 - Copy.jpg
- [x] Space in filename:  ./afyfe/prarielily - Copy.jpg
- [x] Space in filename:  ./afyfe/prarielily2 - Copy.jpg
- [x] Space in filename:  ./afyfe/sink2 (2).JPG
- [x] Invalid Character (: ./afyfe/sink2 (2).JPG
- [x] Invalid Character ): ./afyfe/sink2 (2).JPG
- [x] Space in filename:  ./afyfe/textbackground - Copy.jpg
- [x] Undescriptive name: ./ahasiw/edu.htm
- [x] Undescriptive name: ./ahasiw/epv.htm
- [x] Undescriptive name: ./ahasiw/mix.htm
- [x] Undescriptive name: ./akenderdine/bg.png
- [x] Space in filename:  ./aking/color bursting tiger.jpg
- [x] Space in filename:  ./aking/color conklin_0008.jpg
- [x] Space in filename:  ./aking/color gayland.jpg
- [x] Space in filename:  ./aking/color odyson.jpg
- [x] Space in filename:  ./aking/pic bouy scout photo 2.jpg
- [x] Space in filename:  ./aking/pic_estevan riot.jpg
- [x] Space in filename:  ./aking/pic_king at work photo 1.jpg
- [x] Undescriptive name: ./amckay/1.jpg
- [x] Undescriptive name: ./amckay/2.html
- [x] Undescriptive name: ./amckay/3.jpg
- [x] Undescriptive name: ./amckay/7.jpg
- [x] Undescriptive name: ./anthony/tp.gif
- [x] Undescriptive name: ./bgladwell/art.html
- [x] Undescriptive name: ./bhone/art.css
- [x] Undescriptive name: ./bhone/img/Ant.jpg
- [x] Invalid Character &: ./cepp/CaroleB&W.jpg
- [x] Undescriptive name: ./cepp/epp.jpg
- [x] Space in filename:  ./cepp/domestics/detail of vases2007.png
- [x] Space in filename:  ./cfarrero/worker copy.jpg
- [x] Undescriptive name: ./cgale/art.html
- [x] Undescriptive name: ./cgale/art2.html
- [x] Undescriptive name: ./cwiens/art.html
- [x] Space in filename:  ./dclausen/new  2.txt
- [x] Undescriptive name: ./dgilhooly/images/img-01.jpg
- [x] Undescriptive name: ./dgilhooly/images/wart.jpg
- [x] Undescriptive name: ./djohnson/img/1.jpg
- [x] Undescriptive name: ./djohnson/img/2.jpg
- [x] Undescriptive name: ./djohnson/img/3.jpg
- [x] Undescriptive name: ./djohnson/img/4.jpg
- [x] Undescriptive name: ./djohnson/img/5.jpg
- [x] Undescriptive name: ./djohnson/img/6.jpg
- [x] Undescriptive name: ./dknowles/images/dk1.jpg
- [x] Undescriptive name: ./dknowles/images/dk2.jpg
- [x] Undescriptive name: ./dloran/images/bio.png
- [x] Undescriptive name: ./dmorton/images/FP.jpg
- [x] Undescriptive name: ./dstryjek/artist.jpg
- [x] Space in filename:  ./dthauberger/img/david meeting.jpg
- [x] Space in filename:  ./dthauberger/img/david thauberger.jpg
- [x] Space in filename:  ./dyobb/pics/._PortraitBruceTheMacho - good.jpg
- [x] Space in filename:  ./dyobb/pics/._PortraitBulstrodeSloughfoot - good.png
- [x] Space in filename:  ./dyobb/pics/._PortraitStalward - good.png
- [x] Space in filename:  ./dyobb/pics/._PortraitTaerha - good.png
- [x] Space in filename:  ./dyobb/pics/._PortraitYorrick - good.png
- [x] Space in filename:  ./dyobb/pics/PortraitBruceTheMacho - old.jpg
- [x] Space in filename:  ./dyobb/pics/PortraitBruceTheMacho - orginal.jpg
- [x] Space in filename:  ./dyobb/pics/PortraitBulstrodeSloughfoot - orginal.jpg
- [x] Space in filename:  ./dyobb/pics/PortraitStalward - orginal.jpg
- [x] Space in filename:  ./dyobb/pics/PortraitTaerha - orginal.jpg
- [x] Space in filename:  ./dyobb/pics/PortraitYorrick - orginal.jpg
- [x] Undescriptive name: ./elindner/e.jpg
- [x] Undescriptive name: ./elindner/l.jpg
- [x] Undescriptive name: ./elindner/picture.jpg
- [x] Undescriptive name: ./gsiwek/artist.jpg
- [x] Space in filename:  ./gsiwek/images/Common Redpoll.jpg
- [x] Space in filename:  ./gsiwek/images/Mrs Fowler.jpg
- [x] Space in filename:  ./gsiwek/images/healthy chair.jpg
- [ ] Space in filename:  ./hbenning/Heather Benning/DOLL hOUSE.docx
- [ ] Space in filename:  ./hbenning/Heather Benning/Field Doll.docx
- [ ] Space in filename:  ./hbenning/Heather Benning/Heather Benning short.docx
- [ ] Space in filename:  ./hbenning/Heather Benning/Heather Benning.docx
- [ ] Space in filename:  ./hbenning/Heather Benning/Though Kil.docx
- [ ] Space in filename:  ./hbenning/Heather Benning/Work Hard.docx
- [ ] Space in filename:  ./hbenning/Heather Benning/doll house.jpg
- [ ] Space in filename:  ./hbenning/Heather Benning/hand kiln.jpg
- [ ] Undescriptive name: ./hbenning/js/demo.js
- [ ] Undescriptive name: ./hyang/artist.jpg
- [ ] Space in filename:  ./hyang/images/Empress Dowager Cixi and Four Imperial.jpg
- [ ] Space in filename:  ./hyang/images/fountain under moonlight.jpg
- [ ] Undescriptive name: ./jdeutscher/art1.html
- [ ] Undescriptive name: ./jdeutscher/art2.html
- [ ] Undescriptive name: ./jdeutscher/art3.html
- [ ] Undescriptive name: ./jdeutscher/art4.html
- [ ] Undescriptive name: ./jdeutscher/art5.html
- [ ] Undescriptive name: ./jdeutscher/art6.html
- [ ] Undescriptive name: ./jdeutscher/pic1.jpg
- [ ] Undescriptive name: ./jdeutscher/pic2.jpg
- [ ] Space in filename:  ./jfafard/T C Douglas 1982.jpg
- [ ] Space in filename:  ./jfafard/coyote 2.jpg
- [ ] Space in filename:  ./jfafard/coyote 3.jpg
- [ ] Space in filename:  ./jfafard/coyote 4.jpg
- [ ] Space in filename:  ./jfafard/coyote 6.jpg
- [ ] Undescriptive name: ./jgoddard/images/bg.gif
- [ ] Undescriptive name: ./jgoddard/images/img1.jpg
- [ ] Undescriptive name: ./jgoddard/images/img2.jpg
- [ ] Undescriptive name: ./jgoddard/images/img3.jpg
- [ ] Undescriptive name: ./jgoddard/images/img4.jpg
- [ ] Undescriptive name: ./jgoddard/images/img5.jpg
- [ ] Undescriptive name: ./jgoddard/images/img6.jpg
- [ ] Undescriptive name: ./jhustak/img/works/1.jpg
- [ ] Undescriptive name: ./jhustak/img/works/2.jpg
- [ ] Undescriptive name: ./jhustak/img/works/3.jpg
- [ ] Undescriptive name: ./jhustak/img/works/4.jpg
- [ ] Undescriptive name: ./jhustak/img/works/5.jpg
- [ ] Undescriptive name: ./jhustak/img/works/6.jpg
- [ ] Undescriptive name: ./jhustak/img/works/7.jpg
- [ ] Undescriptive name: ./jhustak/img/works/8.jpg
- [ ] Undescriptive name: ./jmitchell/images/bg.png
- [ ] Undescriptive name: ./joser/pictures.html
- [ ] Space in filename:  ./joser/images/Westfront 1918 03.JPG
- [ ] Undescriptive name: ./jseverson/bar.gif
- [ ] Undescriptive name: ./jseverson/pmc.bak
- [ ] Undescriptive name: ./jseverson/pmc.htm
- [ ] Undescriptive name: ./jsures/images/img6.jpg
- [ ] Undescriptive name: ./lbeug/images/bee.jpg
- [ ] Undescriptive name: ./mcole/img/martha.jpg
- [ ] Undescriptive name: ./mdavenport/art1.jpg
- [ ] Undescriptive name: ./mdavenport/art2.jpg
- [ ] Undescriptive name: ./mdavenport/art3.jpg
- [ ] Undescriptive name: ./mdavenport/art4.jpg
- [ ] Space in filename:  ./mdavenport/marie profile.doc
- [ ] Undescriptive name: ./mkennedy/art.html
- [ ] Undescriptive name: ./mkennedy/artb.html
- [ ] Undescriptive name: ./mkennedy/js/npm.js
- [ ] Undescriptive name: ./mpeeples/images/bed.jpg
- [ ] Undescriptive name: ./mpeeples/images/dog.jpg
- [ ] Undescriptive name: ./mpeeples/images/enlarged/bed.jpg
- [ ] Undescriptive name: ./mpeeples/images/enlarged/dog.jpg
- [ ] Space in filename:  ./msereda/images/c1998 Michele Sereda Performance.jpg
- [ ] Undescriptive name: ./msexton/photos/day.jpg
- [ ] Undescriptive name: ./msexton/photos/owl.jpg
- [ ] Invalid Character (: ./mv/Delicate_Series_H_(eart).jpg
- [ ] Invalid Character ): ./mv/Delicate_Series_H_(eart).jpg
- [ ] Undescriptive name: ./pmakarow/Portraits/anc.jpg
- [ ] Space in filename:  ./rarnott/images/001 ARNOTT - Eavestrough Painting - 1975.jpg
- [ ] Space in filename:  ./rarnott/images/001 ARNOTT - Flower Bed - 1982.jpg
- [ ] Space in filename:  ./rarnott/images/002 ARNOTT - Spaghetti Painting No.1 -1979.jpg
- [ ] Space in filename:  ./rarnott/images/002 ARNOTT - Untitled (Steel Scissor Plier) - 1987.jpg
- [ ] Invalid Character (: ./rarnott/images/002 ARNOTT - Untitled (Steel Scissor Plier) - 1987.jpg
- [ ] Invalid Character ): ./rarnott/images/002 ARNOTT - Untitled (Steel Scissor Plier) - 1987.jpg
- [ ] Space in filename:  ./rarnott/images/003 ARNOTT - Untitled (Wet Soap with Bubbles) -1988.jpg
- [ ] Invalid Character (: ./rarnott/images/003 ARNOTT - Untitled (Wet Soap with Bubbles) -1988.jpg
- [ ] Invalid Character ): ./rarnott/images/003 ARNOTT - Untitled (Wet Soap with Bubbles) -1988.jpg
- [ ] Space in filename:  ./rarnott/images/003 ARNOTT - YES - 1993.jpg
- [ ] Space in filename:  ./rarnott/images/004 ARNOTT - Leaf Tree (After Rain) - 1995.jpg
- [ ] Invalid Character (: ./rarnott/images/004 ARNOTT - Leaf Tree (After Rain) - 1995.jpg
- [ ] Invalid Character ): ./rarnott/images/004 ARNOTT - Leaf Tree (After Rain) - 1995.jpg
- [ ] Space in filename:  ./rarnott/images/004 ARNOTT - Untitled (Gold Brick) - 1989.jpg
- [ ] Invalid Character (: ./rarnott/images/004 ARNOTT - Untitled (Gold Brick) - 1989.jpg
- [ ] Invalid Character ): ./rarnott/images/004 ARNOTT - Untitled (Gold Brick) - 1989.jpg
- [ ] Space in filename:  ./rarnott/images/005 ARNOTT -  Heart Tree (The Road) - 1997.jpg
- [ ] Invalid Character (: ./rarnott/images/005 ARNOTT -  Heart Tree (The Road) - 1997.jpg
- [ ] Invalid Character ): ./rarnott/images/005 ARNOTT -  Heart Tree (The Road) - 1997.jpg
- [ ] Space in filename:  ./rarnott/images/005 ARNOTT - Silver Diamond Red - 1994.jpg
- [ ] Space in filename:  ./rarnott/images/006 ARNOTT - First Couple - 1999.jpg
- [ ] Space in filename:  ./rarnott/images/007 ARNOTT - Untitled (White Soap Illustration No.3) -  2008.jpg
- [ ] Invalid Character (: ./rarnott/images/007 ARNOTT - Untitled (White Soap Illustration No.3) -  2008.jpg
- [ ] Invalid Character ): ./rarnott/images/007 ARNOTT - Untitled (White Soap Illustration No.3) -  2008.jpg
- [ ] Space in filename:  ./rarnott/images/008 ARNOTT - Monolith - 2013.jpg
- [ ] Space in filename:  ./rarnott/images/008 ARNOTT - Purple Irises with Grass No. 2 - 2014.jpg
- [ ] Space in filename:  ./rarnott/images/009 ARNOTT - Revel - 2013.jpg
- [ ] Space in filename:  ./rarnott/images/010 ARNOTT - Untitled (Eggbeater Screwdriver No. 4) - 2014.jpg
- [ ] Invalid Character (: ./rarnott/images/010 ARNOTT - Untitled (Eggbeater Screwdriver No. 4) - 2014.jpg
- [ ] Invalid Character ): ./rarnott/images/010 ARNOTT - Untitled (Eggbeater Screwdriver No. 4) - 2014.jpg
- [ ] Space in filename:  ./rarnott/images/Hat Cake Painting No.4 (Dripping Chocolate) - 1980.jpg
- [ ] Invalid Character (: ./rarnott/images/Hat Cake Painting No.4 (Dripping Chocolate) - 1980.jpg
- [ ] Invalid Character ): ./rarnott/images/Hat Cake Painting No.4 (Dripping Chocolate) - 1980.jpg
- [ ] Undescriptive name: ./rboyer/art.html
- [ ] Space in filename:  ./regina_5/spray copy.jpg
- [ ] Undescriptive name: ./ring/1.jpg
- [ ] Undescriptive name: ./ring/2.jpg
- [ ] Undescriptive name: ./ring/3.jpg
- [ ] Undescriptive name: ./ring/4.jpg
- [ ] Undescriptive name: ./ring/5.jpg
- [ ] Undescriptive name: ./ring/6.jpg
- [ ] Undescriptive name: ./ring/Ing.JPG
- [ ] Undescriptive name: ./smcleod/bar.gif
- [ ] Undescriptive name: ./tmarner/images/pic1.png
- [ ] Undescriptive name: ./tmarner/images/pic2.png
- [ ] Undescriptive name: ./tmarner/images/pic3.png
- [ ] Undescriptive name: ./tmarner/images/pic4.png
- [ ] Undescriptive name: ./tmarner/images/pic5.png
- [ ] Undescriptive name: ./tmarner/images/pic6.png
- [ ] Undescriptive name: ./tmarner/images/pic7.png
- [ ] Undescriptive name: ./tmarner/images/pic8.png
- [ ] Undescriptive name: ./tmarner/images/pic9.png
- [ ] Undescriptive name: ./wparsons/images.html
- [ ] Undescriptive name: ./wparsons/images.png
- [ ] Undescriptive name: ./wparsons/pic1.png
- [ ] Undescriptive name: ./wparsons/pic2.png
- [ ] Undescriptive name: ./wparsons/pic3.png
- [ ] Undescriptive name: ./wparsons/pic4.png
- [ ] Undescriptive name: ./wparsons/pic5.jpg
- [ ] Space in filename:  ./wschell/images/Ward Grounded  Ink on Birch Panel.jpg
- [ ] Space in filename:  ./wschell/images/Ward Schell Under The Pink Rock - Acrylic onm Canvasink-rock1.jpg
- [ ] Space in filename:  ./wschell/images/ward 1.jpg
- [ ] Space in filename:  ./wschell/images/ward 2 Winter on theRocks.jpg
- [ ] Undescriptive name: ./wtunison/1.jpg
- [ ] Undescriptive name: ./wtunison/homepage/va1.htm
- [ ] Undescriptive name: ./wtunison/homepage/vd1.htm
- [ ] Undescriptive name: ./wtunison/homepage/vi1.htm
- [ ] Undescriptive name: ./wtunison/pictures/ann.jpg
- [ ] Undescriptive name: ./wtunison/pictures/artist.dcr
- [ ] Undescriptive name: ./wtunison/pictures/bg.jpg
- [ ] Undescriptive name: ./wtunison/pictures/dan.jpg
- [ ] Undescriptive name: ./wtunison/pictures/he1.jpg
- [ ] Undescriptive name: ./wtunison/pictures/he2.jpg
- [ ] Undescriptive name: ./wtunison/pictures/he3.jpg
- [ ] Undescriptive name: ./wtunison/pictures/he4.jpg
- [ ] Undescriptive name: ./wtunison/pictures/he5.jpg
- [ ] Undescriptive name: ./wtunison/pictures/hearta.jpg
- [ ] Undescriptive name: ./wtunison/pictures/mac.jpg
- [ ] Undescriptive name: ./wtunison/pictures/pam.jpg

**Comment by gemohandy** [comment]
Note - any fix to this issue _must_ pass the test - otherwise, what's the point?

**Comment by gemohandy** [comment]
Current Status:
Added capitalization test and bug counter to the python script
Fixed A's and B's (first name, not last)
908 errors remaining.

**Comment by gemohandy** [comment]
Note - we are now ignoring reginabellringers.ca for the purposes of this error. It's just too much.

**Comment by synixebrett** [comment]
I am going to consider this closed, the only remaining error in master is the marquee which is being worked on
