### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#334]
SaskArtists needs a logo. Make one, and put it on the Github (we’re working on a site redesign, so we can put it in later.

**Comment by gemohandy** [comment]
@munadikiehl
While I appreciate the enthusiasm, this project is specifically for teaching purposes for MSI Computer Camps, a Canadian summer camp. As such, we will not be accepting outside assistance.

**Comment by munadikiehl** [comment]
Thanks for your feedback.
Best regards!

**Comment by gemohandy** [comment]
@trollmad3 - I'm fairly certain I told you in person to talk to Brett, and he'd inform you of how to go about adding to a repository. However, since you don't seem to have done that, here's a brief run-through:

1. Go to the main page of the SaskArtist's repository, [located here](https://github.com/SaskArtists/SaskArtists)
2. Press the Fork button.
![fork button](https://user-images.githubusercontent.com/16967035/42416907-f80ba756-8237-11e8-8a44-d107cca14b20.png)
3. Wait for Github to finish making the new fork. This is a copy of the SaskArtists branch which belongs to you, and which you can work on safely without worrying about messing anything up for anyone else.
4. Click the "Clone or Download" button, then copy the text in the text box.
![clone or download](https://user-images.githubusercontent.com/16967035/42416928-75593458-8238-11e8-94c5-0fe77c2a5033.png)
5. Open Git Bash, the command line program we use for Git stuff at CompCamps.
6. Navigate to your Documents folder using "cd Documents"
7. Type "git clone " and then paste what you copied earlier. When you run the command, it will set up a local version of your SaskArtists fork, allowing you to work on it on your computer.
8. Move the logo to the new SaskArtists folder, which is in your Documents.
9. Open Atom. Add the SaskArtists folder as a project folder.
10. Open the Git tab of atom, commit your photo, and push it. This is typically how we push, because it's much easier than using the command line.
11. The logo you made is now on your version of the SaskArtist's page. Next, you need to make a Pull Request to try getting us to approve your change. Go back to Github, and on your fork, go to the Pull Requests tab. 
12. Click the "New Pull Request Button". It should be bright green.
13. You'll get a page called "Comparing Changes". For now, you can ignore that - Brett and I will worry about it before approving anything. Just hit the big green "Create Pull Request" button.
14. Fill out the text boxes. The first one should be a short description of what the pull request does, while the second should go into more detail. Then, hit the "Create Pull Request" button.

And that should be it! After that, it's just a matter of waiting for Brett and me to go through the changes you've made, look them over, make sure they don't introduce any errors into the system, and that everything is up to the standards we hold, and then your new logo is in the repository. Kaitlen is working on the homepage, so she'll be the one to actually use it. Until then, it will just sit there doing nothing. 
Hope this helps!
 ~ Bennett

**Comment by trollmad3** [comment]
@gemohandy Thank you!

**Comment by gemohandy** [comment]
We now have a logo - it's the name in green cursive. It fits the colour scheme of the new site, so we're using it.
