### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#336]
Question: how many people visit SaskArtists every day? Answer: Nobody Knows! That’s why we need some analytics stuff. We want to know how often the site is used so we know how big a deal it is.

**Comment by trollmad3** [comment]
Doing this, This seems easy to do.

**Comment by synixebrett** [comment]
Closed by @trollmad3 with faec00791f82c1c2cd8a848b498eae882024afc1
