### ISSUE TITLE
Broken Link on Marlo V

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#356]
On Marlo V's page, there is a link to a "Mysteria Art Gallery". This website seems to have mysteriously vanished, as the link no longer works. Because it is an external site, it is not picked up by the existence test that has been added to the Restructure branch, making it a separate error.

**Comment by synixebrett** [comment]
It has been renamed to the Mata Gallery. The only link I could find for it seems to have a new owner... http://www.matagallery.ca/
