### ISSUE TITLE
mkennedy is unreadable

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#357]
During my research into Marlo V. I noticed our page for Marsha Kennedy is unreadable

**Comment by gemohandy** [comment]
![screen shot 2018-07-08 at 12 12 08 am](https://user-images.githubusercontent.com/16967035/42417285-99c5c3fa-8243-11e8-908e-594a531b5116.png)
Do we have different views of Marsha Kennedy's page? Because white text on a deep blue background looks pretty readable to me.
