### ISSUE TITLE
Missing Photos

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#365]
While some of the broken references detected by existence.py are broken because of renaming from the new standards, some of the photos are actually missing. We either need to remove the links to these missing images, or find replacement images. 
Missing images:
- [x] June Jacobs - a painting called January Light. File name wjjjanlight.jpg
- [ ] David Ross - A photo of David Ross. File name artist.jpg

**Comment by gemohandy** [comment]
Issue #377 covers the third of these, but the other two have images available on the "photos" branch. Keep in mind, we couldn't find January Light, but Wayne found a different painting of hers. Replace wwjjjanlight.jpg in the gallery with the new photo, subaqueous_crocus_venus.jpg, and use one of the photos of David Ross on his page.

**Comment by trollmad3** [comment]
@gemohandy Where can I get the photos?

**Comment by gemohandy** [comment]
As I mentioned, there is a branch called "photos" which has the photos you need. If you need help pulling that branch to your computer, ask Brett - I'm technically in class right now, so I probably shouldn't even be doing this, let alone writing up another description of how to do it. Also, don't touch Iris Hauser for now - she's being handled in a separate issue.

**Comment by trollmad3** [comment]
@gemohandy alright thank you.

**Comment by trollmad3** [comment]
I still have a few questions but I do not want to disturb your class, I will ask you in person @gemohandy

**Comment by gemohandy** [comment]
I'm "multitasking" (i.e. paying more attention to SaskArtists than to my class). What's up? I see you've checked off the David Ross photo. Are you having issues with June Jacobs? As I mentioned before, we couldn't find the work "January Light", but Wayne found a different painting of hers - "Subaqueous Crocus Venus". We're replacing January Light with the new one.

**Comment by trollmad3** [comment]
@gemohandy I can not find a light photo on the branch `photos` for June Jacobs. 
![help](https://user-images.githubusercontent.com/7843719/42650445-a354cdb0-85c9-11e8-9058-595147939d94.PNG) (I don't know if this is it) and I cant find of Iris Hauser. I see her art online but not a IRL photo (her face or something slimier)

**Comment by gemohandy** [comment]
First off, that is what we are using to replace January Light, yes. Second, don't touch Iris Hauser - she is being addressed in a separate issue at this point due to gallery issues. Have you actually been reading what I've written? I'm fairly certain this is the third time I've said both of these things.

**Comment by gemohandy** [comment]
> Replace wwjjjanlight.jpg in the gallery with the new photo, subaqueous_crocus_venus.jpg
> As I mentioned before, we couldn't find the work "January Light", but Wayne found a different painting of hers - "Subaqueous Crocus Venus". We're replacing January Light with the new one.
First two mentions of the January Light replacement
>Issue #377 covers the third of these
> Also, don't touch Iris Hauser for now - she's being handled in a separate issue.
First two mentions of Iris Hauser being covered in a separate issue.

**Comment by gemohandy** [comment]
@trollmad3 - I approved your commit too early. The image is named "artist.jpeg", but it's looking for "artist.jpg". Could you fix this?

**Comment by trollmad3** [comment]
@gemohandy Yes.
