### ISSUE TITLE
Iris Hauser Gallery

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#377]
So, Wayne provided us with a large number of paintings by Iris Hauser. This is a good thing, since most of them seem to have disappeared. Despite the gallery obviously being intended to hold a half dozen images, it only has one. Since we have so many new paintings, they need to be added to the gallery. All of the images are stored, under proper naming conventions, in the irishauser branch of the repository, so you should work off of that when doing this.

**Comment by RyenRerbertson** [comment]
added images.
