### ISSUE TITLE
Changelog for David Thaumberger

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#378]
Javin - you may have added your name to the page itself, but we now have a changelog in the actual files. Check the artist.json file in dthaumberger. You need to add a new item to the list of changes mentioning that you updated the website in 2018.

**Comment by trollmad3** [comment]
@gemohandy So I delete my name and put it in `artist.json`?

**Comment by gemohandy** [comment]
I'm not certain this is closed - I haven't approved pull request #379 yet because the rest of the changelogs follow a standard format, which yours doesn't seem to conform to. I keep meaning to speak with @synixebrett about whether or not this is important enough to stop it from going through.
