### ISSUE TITLE
Some pages should be hidden

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#398]
**Describe the bug**
A few of the artists are not supposed to be visible on the SaskArtist homepage, notably the Regina Bell Ringers. We need to hide the artists that we don't want visible as some of them have previously requested their pages be taken down, and they are now once again up.

**Additional context**
Wayne mentioned the artists to me that were supposed to be taken down, I can not remember all of them. He said a list was given to @kzastrow01.

**Comment by trollmad3** [comment]
If I get the list, I can take them down.

**Comment by synixebrett** [comment]
We don't want to get rid of the code though, we just want to hide them on the homepage.

**Comment by trollmad3** [comment]
Okay.

**Comment by trollmad3** [comment]
@synixebrett Do you think we can create a `403 forbidden` page for the ones that should be hidden?

**Comment by synixebrett** [comment]
`410 Gone` would be more applicable here

**Comment by synixebrett** [comment]
This might have to wait until I can get in contact with Wayne, which might not be until June

**Comment by trollmad3** [comment]
@synixebrett Alright.

**Comment by trollmad3** [comment]
This issue will now have the wontfix tag because we cannot get the list from Wayne.

**Comment by synixebrett** [comment]
I have received the list from Wayne and will be solving this issue.
