### ISSUE TITLE
External Images

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#412]
We should not allow the use of external images inside the artists folder, a script should be written and added to the CircleCI workflow.

We have sites created 10+ years ago that aren't view-able because they used external image hosts that are no longer around.

**Comment by trollmad3** [comment]
Is there a list of artists using external image sites or do we need to find them ourselves?

**Comment by synixebrett** [comment]
A search for `src=['"]http` will show us any thing using an external source

**Comment by trollmad3** [comment]
@synixebrett I search for that in the folder of all the artists?

**Comment by synixebrett** [comment]
Yes, you'll need to enable the regex search feature of whatever editor you use

**Comment by AndrewJMD** [comment]
closed in #472
