### ISSUE TITLE
Home Page Info

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#420]
Our home page, https://saskartists.ca, has a brief description of the SaskArtists project. However, there are some details which should be added:

- [ ]  First pages made in 1995
- [ ]  Annual update cycle
- [ ]  We try to keep things current and correct

This information should be added to the information currently on the page - possibly modifying the "Our Goals" section, and maybe adding a new section?

**Comment by eli9701** [comment]
fixes #420

**Comment by synixebrett** [comment]
Closed by #447
