### ISSUE TITLE
June Mitchell - Update Content

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#437]
June Mitchell's page has a few things that need update:
 - She's published some books which we should probably mention
 - Wayne wants her to come in and get interviewed. If you got assigned to this, it's your job to interview her and put the relevant stuff on the website.

**Comment by kzastrow01** [comment]
This one is now linked with the powerpoints, as one of them is broken, so Wayne wants to add more than just that one. He wants to make some brand new ones.
