### ISSUE TITLE
Circle CI testing file names in Build folder

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#444]
Circle CI currently tests the file names in the Build folder, which is where we keep the scripts used to build. While we don't have to worry about recursive issues (yet), it is currently throwing an error because of a script named "test.py", which is an undescriptive name. We can either exclude the Build folder from the descriptive name test, or we can rename it to something adequetly descriptive. Either way, this needs to be done ASAP, because we need to remove all the red Xs as quickly as possible, and this is currently the only error.

**Comment by synixebrett** [comment]
Add an exception, that file has a class called Test so it is a descriptive name
