### ISSUE TITLE
cepp spelling

### ISSUE THREAD

**Issue by synixebrett** [SaskArtists/SaskArtists#486]
/cepp is spelled two different ways

Carole Epp
Carol Epp

We need to find the correct spelling and correct all the incorrect versions.

**Comment by Aholicknight** [comment]
I can't find the website on saskartists.ca
![image](https://user-images.githubusercontent.com/7843719/61225104-24fc2b80-a6dd-11e9-9e72-52edc1070a58.png)

**Comment by kzastrow01** [comment]
It is confirmed spelt by Wayne as 'Carol'
