### ISSUE TITLE
Robert Bettridge

### ISSUE THREAD

**Issue by kzastrow01** [SaskArtists/SaskArtists#489]
New artist, will be here 3:30pm - supper on wednesday.

**Comment by Aholicknight** [comment]
Should I record this?

**Comment by kzastrow01** [comment]
What do you mean by 'record it'?

**Comment by Aholicknight** [comment]
@kzastrow01 If he did a talk or showed any important art, it would be a good idea to record it or take a picture of it to add it on the website.

**Comment by Aholicknight** [comment]
I can probably bring a camera or record it off my phone tomorrow.

**Comment by kzastrow01** [comment]
Why? Just take notes on your photo. Bring your phone to take photos, always. But you don't need to record it.
