### ISSUE TITLE
Replace Link with Actual Form

### ISSUE THREAD

**Issue by gemohandy** [SaskArtists/SaskArtists#70]
I don't feel comfortable using a simple link to GitHub. It doesn't link back to the artist database, and I think it might require a GitHub account, which most non-development folk probably don't have. As such, I would prefer to create a PHP form on the Sask Artists page that allows you to create an error on GitHub from our site.

How to encounter the problem:
1. Click on the link at the bottom of the page. You get sent to GitHub, and have to press the back arrow to get back to our database.

**Comment by BmanDesignsCanada** [comment]
The GitHub does link back.

**Comment by BmanDesignsCanada** [comment]
We may add a form,
