### ISSUE TITLE
Remove index page from database entries

### ISSUE THREAD

**Issue by BmanDesignsCanada** [SaskArtists/SaskArtists#85]
In the database each artists has their index page marked. I want the page removed so it is only a link to their folder.

**Comment by gemohandy** [comment]
UPDATE artists as a1 INNER JOIN artists as a2  ON a1.id = a2.id SET a1.short=LEFT(a2.short,LOCATE('/',a2.short)-1) WHERE a1.short LIKE '%/%'

**Comment by BmanDesignsCanada** [comment]
Executed in production.
