### ISSUE TITLE
amckay rename home to index

### ISSUE THREAD

**Issue by BmanDesignsCanada** [SaskArtists/SaskArtists#89]

**Comment by gemohandy** [comment]
He does have an index; it's just a completely useless index that just links to the info page.

**Comment by BmanDesignsCanada** [comment]
Leaving it how it is.

**Comment by BmanDesignsCanada** [comment]
Change "Click Below to Continue" to "Click Here to Continue" and make it a link.
The image can also remain as a link.
This will make the page more intuitive.
